version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3307:3306" # Mapare porturi: 3307 local -> 3306 container
    volumes:
      - mysql_data:/var/lib/mysql # Corectare volum
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data: # Declarare volum pentru persistență
